title: Finite & Learnable
description: A corner to share my understanding of various mathematical topics, in a fun way (but not always).  
theme: jekyll-theme-minimal
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax

# hide the GitHub box
show_downloads: false
github:
  is_user_page: false
  is_project_page: false
